spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pulse
    username: pulse_user
    password: pulse_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

server:
  port: 8080