services:
  postgres:
    image: postgres:16
    container_name: pulse_db
    environment:
      POSTGRES_DB: pulse
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: